redis_url: &redis_url
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>

development:
  adapter: redis
  <<: *redis_url

test:
  adapter: test

production:
  adapter: redis
  <<: *redis_url
  channel_prefix: lokic_production
