module TrackingHoursHelper
  def types_of_work
    ['Data Collection and Processing',
    'DWYM',
    'General Management',
    'G&A Development Services',
    'G&A Management- Data Services',
    'Story Production',
    'Lead Generation',
    'Data Cleaning',
    'Roseland MVP',
    'Cost Of Sales - Ballotpedia',
    'FOIA Chargers',
    'Franklin Archer Social Media',
    'Blockshopper Customer Service',
    "Data Analysis - Voter Profile 'Grid'",
    'Dev Algo work',
    'Application Maintenance',
    'Human Resources - Hiring Skill test',
    'Matching Algos',
    'Physical Hardware Cost',
    'Scrape sourcing, instructions and data review',
    'Data Collection',
    'Data Matching',
    'G&A Management- Human Resources',
    'Scrape Work']
  end

  def clients
    ['AbelsonTaylor',
    'All Texas Process Servers',
    'American Independent Media',
    'Arizona Prosperity Alliance',
    'Austin American-Statesman',
    'Beaumont Enterprise',
    'Berkeley Research Group',
    'Configure One',
    'Curious Task',
    'D181 School Board Campaign',
    'Dan Proft',
    'Delos Communications',
    'Digital Logic',
    'DirecTech',
    'Edelman',
    'Empower Texans',
    'Everett Herald',
    'File & ServeXpress',
    'Financial Poise',
    'Fisher Wallace Laboratories',
    'Franklin News Foundation',
    'Genus Holdings',
    'Georgetown Group',
    'Google AdSense',
    'Grocery Manufacturers Association',
    'Heartland Institute',
    'Houston Chronicle',
    'Hutchinson & Stoy PLLC',
    'Illinois Business Alliance',
    'Illinois Opportunity Project',
    'Illinois Policy Institute',
    'Illinois Policy(501c3)',
    'IMGE',
    'INN-Watchdog.org',
    'Iowa Digital Newsboard',
    'Ironlight',
    'Ives for Illinois',
    'Kin',
    'Kivvit',
    'Liberty Principals PAC',
    'Lisa Wagner Co.',
    'Litify',
    'Local Government Information Services',
    'Local Labs',
    'Local Labs - Shared Services',
    'Metric Media',
    'Project 5 Media',
    'Real Time Reporters',
    'Red Dog Dumpsters',
    'Satter Foundation',
    'Satter Management',
    'Scripps Media',
    'Semiotics',
    'Shaw Media',
    'Shorewood Development Group',
    'Situation Management Group',
    'Spiegel',
    'Steve Lefko - School Board',
    'Texas Monitor',
    'Texas Public Policy Foundation',
    'The Record',
    'Tiger Swan',
    'Timothy Broas',
    'Toba Communications',
    'Trident CEO Council',
    'Two Dog Blog',
    'US Term Limits',
    'WV Bar Association',
    'Zola Creative',
    'Zurich North America',
    'Ballotpedia',
    'Blockshopper',
    'ASC',
    'Roseland',
    'Situation Management Group (SMG)',
    'Broomfield, CO - Big Dog Promotion',
    'G&A Management- Data Services',
    'G&A Development Services',
    'Lumen',
    'G&A Management- Human Resources',
    'urban business underwriting',
    'catholic vote']
  end

end
